Feature home
Kronicle-team/kronicle-app pull request #11
Opened 2022-03-28 10:48 UTC by rider3458

Card showcase shows fewer cards in lower width screens. When test with lower width screens, refresh the page when you see the cards overflow out of the main element.

2022-03-29 10:35 UTC, doanyennhi requested changes
- More spacing between heading and "More"
- More margin between sections (between scan and latest bid, between latest bid and latest product)
- More feedback when hovering over chevron buttons and "More"

2022-03-29 10:59 UTC, doanyennhi commented on src/components/CardShowCase.js
> +           <button onClick={() => {
- Please make this into the ToggleButton component (already have the JS file in components) as this may be used in other pages

2022-03-31 10:51 UTC, doanyennhi requested changes
- The switch page (toggle) buttons in All page is not working properly
- Responsive in All page is weird
- No feedback when hovering over toggle buttons

2022-04-01 07:49 UTC, rider3458 commented
change color of pagination btn (current page has darker color)
disable next btn on max page
home page togglebtn hover cursor pointer

2022-04-02 13:56 UTC, doanyennhi approved these changes

2022-04-02 14:06 UTC, tnathu-ai approved these changes

2022-04-02 14:07 UTC, minhthuhua72 approved these changes

2022-04-02 14:07 UTC, hlinh88 approved these changes

2022-04-02 14:07 UTC, merged