Manh
Kronicle-team/kronicle-app pull request #7
Opened 2022-03-13 23:30 UTC by rider3458

- Legal pages
- Login+ register
- Product detail
- User profile

2022-03-14 04:03 UTC, doanyennhi requested changes
- Replace class attribute with className as React uses className or delete all class attributes as we are not using it yet

2022-03-14 04:03 UTC, doanyennhi commented on src/pages/auth/LoginPage.js
> +        </form>
Forgot submit button here. Also you can make this button a component to be reused across many pages

2022-03-14 15:02 UTC, rider3458 commented
wrong push description, the problem was with the content of Privacy Policy

2022-03-15 07:41 UTC, doanyennhi submitted a review, later dismissed

2022-03-15 07:46 UTC, doanyennhi approved these changes

2022-03-15 07:46 UTC, merged